# Testing the code base against the Meilisearch pre-releases
name: Pre-Release Tests

# Will only run for PRs and pushes to bump-meilisearch-v*
on:
  push:
    branches: bump-meilisearch-v*
  pull_request:
    branches: bump-meilisearch-v*

env:
  CARGO_TERM_COLOR: always

jobs:
  integration_tests:
    name: integration-tests-against-rc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: cargo build --verbose
      - name: Get the latest Meilisearch RC
        run: echo "MEILISEARCH_VERSION=$(curl https://raw.githubusercontent.com/meilisearch/integration-guides/main/scripts/get-latest-meilisearch-rc.sh | bash)" >> $GITHUB_ENV
      - name: Meilisearch (${{ env.MEILISEARCH_VERSION }}) setup with Docker
        run: docker run -d -p 7700:7700 getmeili/meilisearch:${{ env.MEILISEARCH_VERSION }} meilisearch --master-key=masterKey --no-analytics
      - name: Run tests
        run: cargo test --verbose -- --test-threads=1
